project:
  type: book
  resources:
    - "/htmls-and-sources/"
    - "/art/"

book:
  title: "Awash in Data"
  description: An introduction to Data Science and data moves with CODAP
  author: "Tim Erickson"
  date: today
  sidebar: 
    collapse-level : 1
    search: true
    background: light
  chapters:
    - href: index.qmd
      text: Introduction
    - part: 01-lesson-part.qmd
      text: Lessons
      chapters: 
        - 01.10-start.qmd
        - 01.20-teens.qmd
        - 01.30-assignment-1.qmd
        - 01.40-teens2.qmd
        - 01.50-assignment-2.qmd
        - 01.60-project.qmd
    - part: 03-datamove-part.qmd
      chapters:
        - 03.10-Filtering.qmd
        - 03.20-Grouping.qmd
        - 03.30-Calculating.qmd
        - 03.40-Summarizing.qmd
        - 03.50-Joining.qmd
        - href: 03.60-preparing-and-cleaning.qmd
          text: Munging data
        - 03.70-visualization.qmd
    - part: 04-codap-part.qmd
      chapters:
        - 04.10-types-of-attributes.qmd
        - 04.20-save-import-export-share.qmd
        - 04.30-screen-space.qmd
        - 04.40-graphing-tips.qmd
        - 04.50-dates-and-times.qmd
        - 04.60-maps.qmd
        - 04.70-adjustment-and-control.qmd
        - 04.80-plugin-logistics.qmd
    - part: 06-projects-part.qmd
      chapters:
        - 06.50-world-bank-data.qmd
        - 06.80-data-moves-portfolio.qmd
    - part: 07-stats-part.qmd
      text: Prob and Stats
      chapters:
        - 07.10-binomial.qmd
        - href: 07.20-scrambling.qmd
          text: Scrambling
        - href: 07.30-bootstrap.qmd
          text: Bootstrap
        - href: 07.40-inference-intermezzo.qmd
          text: Intermezzo
        - href: 07.60-tangerines-redux.qmd
          text: More tangerines
    - part: 21-portal-part.qmd
      text: Data Portals
      chapters:
        - href: 21.10-census-acs.qmd
          text: Census and ACS
        - 21.20-BART.qmd
        - 21.30-noaa-weather.qmd
        - 21.40-nhanes-portal.qmd
    - href: 31-other-cool-tools.qmd
      text: "Other cool tools"
    - references.qmd

appendices:

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: awash.css
  pdf:
    documentclass: scrreprt



