project:
  type: book

book:
  title: "Awash in Data"
  author: "Tim Erickson"
  date: "3/4/2023"
  search: true
  chapters:
    - index.qmd
    - 00-intro.qmd
    - part: 01-lesson-part.qmd
      chapters: 
        - 01.10-start.qmd
        - 01.20-teens.qmd
        - 01.30-assignment-1.qmd
        - 01.40-teens2.qmd
        - 01.50-assignment-2.qmd
        - 01.60-project.qmd
    - part: 03-datamove-part.qmd
      chapters:
        - 03.10-Filtering.qmd
        - 03.20-Grouping.qmd
        - 03.30-Calculating.qmd
        - 03.40-Summarizing.qmd
        - 03.50-Joining.qmd
        - href: 03.60-preparing-and-cleaning.qmd
          text: Munging data
        - 03.70-visualization.qmd
    - part: 04-codap-part.qmd
      chapters:
        - 04.10-types-of-attributes.qmd
        - 04.20-save-import-export-share.qmd
        - 04.30-screen-space.qmd
        - 04.40-graphing-tips.qmd
        - 04.50-dates-and-times.qmd
        - 04.60-maps.qmd
        - 04.70-adjustment-and-control.qmd
        - 04.80-plugin-logistics.qmd
    - part: 06-projects-part.qmd
      chapters:
        - 06.50-world-bank-data.qmd
        - 06.80-data-moves-portfolio.qmd
    - part: 07-stats-part.qmd
      text: Prob and Stats
      chapters:
        - 07.10-binomial.qmd
        - href: 07.20-scrambling.qmd
          text: Scrambling
        - href: 07.30-bootstrap.qmd
          text: Bootstrap
    - part: 08-arbor/08-arbor-part.qmd
      text: Trees with Arbor
      chapters:
        - 08-arbor/08.10-arbor-anatomy.qmd
        - 08-arbor/08.20-arbor-begin.qmd
        - href: 08-arbor/08.30-arbor-with-graphs.qmd
        - href: 08-arbor/08.40-arbor-fbola.qmd
        - href: 08-arbor/08.50-arbor-measures.qmd
        - href: 08-arbor/08.60-arbor-breast-cancer.qmd
          text: Breast cancer example 
        - href: 08-arbor/08.80-arbor-and-ml.qmd
        - href: 08-arbor/08.90-arbor-configuration.qmd
          text: Configuring a node
    - part: 21-portal-part.qmd
      text: Data Portals
      chapters:
        - href: 21.10-census-acs.qmd
          text: Census and ACS
        - 21.20-BART.qmd
        - 21.30-noaa-weather.qmd
        - 21.40-nhanes-portal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: awash.css
  pdf:
    documentclass: scrreprt



