project:
  type: book

book:
  title: "Awash in Data"
  author: "Tim Erickson"
  date: "3/4/2023"
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: 01-lesson-part.qmd
      chapters: 
        - 01.10-start.qmd
        - 01.20-teens.qmd
        - 01.30-assignment-1.qmd
        - 01.40-teens2.qmd
        - 01.50-assignment-2.qmd
        - 01.60-project.qmd
    - part: 02-portal-part.qmd
      chapters:
        - 02.10-census-acs.qmd
        - 02.20-BART.qmd
        - 02.30-noaa-weather.qmd
        - 02.40-nhanes-portal.qmd
    - part: 03-datamove-part.qmd
      chapters:
        - 03.10-Filtering.qmd
        - 03.20-Grouping.qmd
        - 03.30-Calculating.qmd
        - 03.40-Summarizing.qmd
        - 03.50-Joining.qmd
        - 03.60-preparing-and-cleaning.qmd
        - 03.70-visualization.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: awash.css
  pdf:
    documentclass: scrreprt



